id: P004505
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W30478
  title: ཤན་འདན་ནང་འཁྲུག་དང་ཤེལ་བྲག་འོ་མཚོའི་གཏེར་གཡང་།
  author: ''
  volumes:
    c96ee96cc48449c38b627b53d47db935:
      image_group_id: I1KG16934
      title: ''
      volume_number: 1
      total_pages: 308
      base_file: v001.txt
