id: I9F07D0EF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T07:52:41+00:00'
last_modified: '2022-06-08T01:33:29.553019+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30478
  title: ཤན་འདན་ནང་འཁྲུག་དང་ཤེལ་བྲག་འོ་མཚོའི་གཏེར་གཡང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    5EA8:
      image_group_id: I1KG16934
      title: ''
      total_pages: 308
      order: 1
      base_file: 5EA8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
